DIST_SUBDIRS =		\
	docinfo 	\
	externaltools	\
	modelines	\
	pythonconsole	\
	snippets	\
	sort 		\
	spell 		\
	taglist 	\
	terminal	\
	time		\
	trailsave

SUBDIRS = 		\
	docinfo		\
	externaltools	\
	modelines	\
	pythonconsole	\
	snippets	\
	sort		\
	taglist		\
	terminal	\
	time		\
	trailsave

if ENABLE_ENCHANT
SUBDIRS      += spell
endif

-include $(top_srcdir)/git.mk
