if build_bundled_python_loader
  subdir('pythonloader')
endif

subdir('docinfo')
subdir('externaltools')
subdir('filebrowser')
subdir('modelines')
subdir('pythonconsole')
subdir('quickopen')
subdir('snippets')
subdir('sort')
if enable_spell
  subdir('spell')
endif
subdir('taglist')
subdir('time')
subdir('trailsave')
