python_files = [
  '__init__.py',
  'capture.py',
  'library.py',
  'functions.py',
  'manager.py',
  'outputpanel.py',
  'filelookup.py',
  'linkparsing.py',
]

install_data(python_files,
  install_dir: join_paths(pkglibdir, 'plugins/externaltools')
)

install_data(['tools.ui', 'outputpanel.ui'],
  install_dir: join_paths(pkgdatadir, 'plugins/externaltools/ui')
)
