python_files = [
  '__init__.py',
  'comment.py',
  'Completion.py',
  'Document.py',
  'Exporter.py',
  'Helper.py',
  'Importer.py',
  'LanguageManager.py',
  'Library.py',
  'Manager.py',
  'Parser.py',
  'Placeholder.py',
  'Snippet.py',
  'SubstitutionParser.py',
  'WindowHelper.py',
]

install_data(python_files,
  install_dir: join_paths(pkglibdir, 'plugins/snippets')
)

install_data('snippets.ui',
  install_dir: join_paths(pkgdatadir, 'plugins/snippets')
)
