subdir('lang')

snippets_data = [
  'css.xml',
  'c.xml',
  'cpp.xml',
  'chdr.xml',
  'docbook.xml',
  'fortran.xml',
  'global.xml',
  'haskell.xml',
  'html.xml',
  'idl.xml',
  'javascript.xml',
  'java.xml',
  'latex.xml',
  'mallard.xml',
  'perl.xml',
  'php.xml',
  'python.xml',
  'ruby.xml',
  'sh.xml',
  'snippets.xml',
  'tcl.xml',
  'xml.xml',
  'xslt.xml',
  'lua.xml',
]

install_data(snippets_data,
  install_dir: join_paths(pkgdatadir, 'plugins/snippets')
)

install_data('snippets-runtime.lua',
  install_dir: join_paths(pkgdatadir, 'plugins/snippets')
)
