ignore_h_files = [
  'pluma-commands.h',
  'pluma-document-loader.h',
  'pluma-document-saver.h',
  'pluma-documents-panel.h',
  'pluma-io-error-message-area.h',
  'pluma-languages-manager.h',
  'pluma-plugins-engine.h',
  'pluma-prefs-manager-private.h',
  'pluma-session.h',
  'pluma-ui.h',
  'pluma-window-private.h',
  'pluma-output-window.h',
  'pluma-close-confirmation-dialog.h',
  'pluma-encodings-dialog.h',
  'pluma-open-location-dialog.h',
  'pluma-page-setup-dialog.h',
  'pluma-preferences-dialog.h',
  'pluma-search-dialog.h',
  'pluma-marshal.h',
  'pluma-enum-types.h',
  'bacon-message-connection.h',
  'plumatextregion.h',
  'sexy-icon-entry.h',
]

gnome.gtkdoc('pluma',
  main_sgml: 'pluma-docs.sgml',
  src_dir: join_paths(meson.project_source_root(), 'pluma'),
  dependencies: pluma_deps,
  gobject_typesfile: 'pluma.types',
  scan_args: ['--deprecated-guards=GTK_DISABLE_DEPRECATED'],
  ignore_headers: ignore_h_files,
  install: true,
)
